GET http://localhost:9527/simple/single?nae=99&age=9
Accept: application/json

###
POST http://localhost:9527/simple/form
Content-Type: application/x-www-form-urlencoded

id=99&age=1

###
POST http://localhost:9527/simple/json
Content-Type: application/json

{
  "id": 1,
  "name": "test",
  "age": 9,
  "address": "testxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}

###
